### ISSUE TITLE
Firefox Quick Find triggers when typing '

### ISSUE THREAD

**Issue by precondition** [callum-oakley/nonsense#1]
Firefox has a feature called "Quick Find" which lets the user open a link using purely the keyboard. It gets triggered by <kbd>'</kbd>. Normally, you can still type ' just fine in text fields and so forth without opening up the Quick Find menu every time but that doesn't seem to apply to your site.

For reference, this option can be disabled globally by setting `accessibility.typeaheadfind.manual` to `false` in `about:config`.
(Note: Tridactyl's equivalent jump to links feature, bound to fF still works even if that option is set to false)

How to reproduce:
1. Open Firefox
2. Make sure `accessibility.typeaheadfind.manual` is set to `true` in `about:config`
3. Press <kbd>'</kbd>
4. ![result](https://i.imgur.com/MxZ0ejE.png)

Pressing <kbd>/</kbd> also pops up Quick Find but that's unlikely to appear in the list of words.

**Comment by callum-oakley** [comment]
Thanks for reporting this, should be fixed now. :)
